repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        files: ^(bayesdawn/(algebra|gaps)/.*\.py|bayesdawn/datamodel\.py)$
      - id: ruff-format
        files: ^(bayesdawn/(algebra|gaps)/.*\.py|bayesdawn/datamodel\.py)$